   
language: python
python:
  - "3.7"
jobs:
  include:
    - stage: development
      install: 
      - pip install pytest
      - pip install --upgrade pip
      script: pytest
    - stage: tests
      install: pip install pytest
      script: pytest
    - stage: stage
      install: pip install pytest
      script: pytest