   
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
jobs:
  include:
    - stage: stage
      install: pip install pytest
      script: pytest
    - stage: test
      install: pip install pytest
      script: pytest
    - stage: build
      install: pip install pytest
      script: pytest