   
language: python
python:
  - "3.7"
jobs:
  include:
    - stage: stage
      install: pip install pytest
      script: pytest
    - stage: test
      install: pip install pytest
      script: pytest
    - stage: build
      install: pip install pytest
      script: pytest